animal = "  chancHito feliz  "
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.lstrip())
print(animal.rstrip())
print(animal.find("c"))
print(animal.replace("nCH", "j"))
print("nCH" in animal)
print("nCH" not in animal)
